# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Revlytic"
client_id = "d733a4696305f73394b07285ed5794f6"
application_url = "https://revlytic.co"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true
scopes="write_products,read_translations,read_themes,read_products,write_products,read_discounts,write_discounts,read_customers ,write_customers,read_all_orders,read_orders,write_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_price_rules,unauthenticated_write_checkouts ,read_own_subscription_contracts,write_own_subscription_contracts,read_customer_payment_methods,unauthenticated_read_product_listings,unauthenticated_read_product_tags"
[auth]
redirect_urls = [
  "https://revlytic.co/auth/callback",
  "https://revlytic.co/auth/shopify/callback",
  "https://revlytic.co/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://revlytic.co/api/webhooks"
  customer_data_request_url = "https://revlytic.co/api/webhooks"
  shop_deletion_url = "https://revlytic.co/api/webhooks"

[app_proxy]
url = "https://revlytic.co/api/storefront/appProxy"
subpath = "revlytic-subscriptions"
prefix = "apps"

[pos]
embedded = false
