# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "revlytic-staging"
client_id = "ab6ae3beb20057645413bb2dd8200390"
application_url = "https://dev.revlytic.co"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://dev.revlytic.co/api/auth/shopify/callback",
  "https://dev.revlytic.co/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://dev.revlytic.co/api/webhooks"
  customer_data_request_url = "https://dev.revlytic.co/api/webhooks"
  shop_deletion_url = "https://dev.revlytic.co/api/webhooks"

[pos]
embedded = false
