
export  const countryCodes = ["AF", "AX", "AL", "DZ", "AD", "AO", "AI", "AG", "AR", "AM", "AW", "AC", "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BA", "BW", "BV", "BR", "IO", "BN", "BG", "BF", "BI", "KH", "CA", "CV", "BQ", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO", "KM", "CG", "CD", "CK", "CR", "HR", "CU", "CW", "CY", "CZ", "CI", "DK", "DJ", "DM", "DO", "EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP", "GT", "GG", "GN", "GW", "GY", "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM", "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "XK", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU", "MO", "MG", "MW", "MY", "MV", "ML", "MT", "MQ", "MR", "MU", "YT", "MX", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "AN", "NC", "NZ", "NI", "NE", "NG", "NU", "NF", "MK", "NO", "OM", "PK", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "QA", "CM", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "GS", "KR", "SS", "ES", "LK", "VC", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK", "TO", "TT", "TA", "TN", "TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "US", "UM", "UY", "UZ", "VU", "VE", "VN", "VG", "WF", "EH","YE","ZM","ZW","ZZ"];


export const countryList=["Afghanistan","Aland Islands","Albania","Algeria","Andorra","Angola","Anguilla","Antigua And Barbuda","Argentina","Armenia","Aruba","Ascension Island","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia And Herzegovina","Botswana","Bouvet Island","Brazil","British Indian Ocean Territory","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde","Caribbean Netherlands","Cayman Islands","Central African Republic","Chad","Chile","China","Christmas Island","Cocos (Keeling) Islands","Colombia","Comoros","Congo","Congo, The Democratic Republic Of The","Cook Islands","Costa Rica","Croatia","Cuba","Curaçao","Cyprus","Czech Republic","Côte d'Ivoire","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Guiana","French Polynesia","French Southern Territories","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guadeloupe","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana","Haiti","Hong Kong SAR","Hungary","Iceland","India","Indonesia","Iraq","Ireland","Isle Of Man","Israel","Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kiribati","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macao SAR","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Martinique","Mauritania","Mauritius","Mayotte","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Myanmar (Burma)","Namibia","Nauru","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Niue","Norfolk Island","North Macedonia","Norway","Oman","Pakistan","Palestinian Territories","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Pitcairn Islands","Poland","Portugal","Qatar","Reunion","Romania","Russia","Rwanda","Samoa","San Marino","Sao Tome And Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Georgia And The South Sandwich Islands","South Korea","South Sudan","Spain","Sri Lanka","St. Barthélemy","St. Helena","St. Kitts &; Nevis","St. Lucia","St. Martin","St. Pierre & Miquelon","St. Vincent & Grenadines","Sudan","Suriname","Svalbard And Jan Mayen","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania, United Republic Of","Thailand","Timor Leste","Togo","Tokelau","Tonga","Trinidad and Tobago","Tristan da Cunha","Tunisia","Turkey","Turkmenistan","Turks and Caicos Islands","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","United States Minor Outlying Islands","Uruguay","Uzbekistan","Vanuatu","Venezuela","Vietnam","Wallis And Futuna","Western Sahara","Yemen","Zambia","Zimbabwe"];


export const countriesAndCurrencyCode = [
    {name: "Afghanistan",currency: "AFN"},
    {name: "Aland Islands",currency: "EUR"},
    {name: "Albania",currency: "ALL"},
    {name: "Algeria",currency: "DZD"},
    {name: "American Samoa",currency: "USD"},
    {name: "Andorra",currency: "EUR"},
    {name: "Angola",currency: "AOA"},
    {name: "Anguilla",currency: "XCD"},
    {name: "Antarctica",currency: "AAD"},
    {name: "Antigua and Barbuda",currency: "XCD"},
    {name: "Argentina",currency: "ARS"},
    {name: "Armenia",currency: "AMD"},
    {name: "Aruba",currency: "AWG"},
    {name: "Australia",currency: "AUD"},
    {name: "Austria",currency: "EUR"},
    {name: "Azerbaijan",currency: "AZN"},
    {name: "Bahamas",currency: "BSD"},
    {name: "Bahrain",currency: "BHD"},
    {name: "Bangladesh",currency: "BDT"},
    {name: "Barbados",currency: "BBD"},
    {name: "Belarus",currency: "BYN"},
    {name: "Belgium",currency: "EUR"},
    {name: "Belize",currency: "BZD"},
    {name: "Benin",currency: "XOF"},
    {name: "Bermuda",currency: "BMD"},
    {name: "Bhutan",currency: "BTN"},
    {name: "Bolivia",currency: "BOB"},
    {name: "Bonaire, Sint Eustatius and Saba",currency: "USD"},
    {name: "Bosnia and Herzegovina",currency: "BAM"},
    {name: "Botswana",currency: "BWP"},
    {name: "Bouvet Island",currency: "NOK"},
    {name: "Brazil",currency: "BRL"},
    {name: "British Indian Ocean Territory",currency: "USD"},
    {name: "Brunei Darussalam",currency: "BND"},
    {name: "Bulgaria",currency: "BGN"},
    {name: "Burkina Faso",currency: "XOF"},
    {name: "Burundi",currency: "BIF"},
    {name: "Cambodia",currency: "KHR"},
    {name: "Cameroon",currency: "XAF"},
    {name: "Canada",currency: "CAD"},
    {name: "Cape Verde",currency: "CVE"},
    {name: "Cayman Islands",currency: "KYD"},
    {name: "Central African Republic",currency: "XAF"},
    {name: "Chad",currency: "XAF"},
    {name: "Chile",currency: "CLP"},
    {name: "China",currency: "CNY"},
    {name: "Christmas Island",currency: "AUD"},
    {name: "Cocos (Keeling) Islands",currency: "AUD"},
    {name: "Colombia",currency: "COP"},
    {name: "Comoros",currency: "KMF"},
    {name: "Congo",currency: "XAF"},
    {name: "Congo, Democratic Republic of the Congo",currency: "CDF"},
    {name: "Cook Islands",currency: "NZD"},
    {name: "Costa Rica",currency: "CRC"},
    {name: "Cote D'Ivoire",currency: "XOF"},
    {name: "Croatia",currency: "HRK"},
    {name: "Cuba",currency: "CUP"},
    {name: "Curacao",currency: "ANG"},
    {name: "Cyprus",currency: "EUR"},
    {name: "Czech Republic",currency: "CZK"},
    {name: "Denmark",currency: "DKK"},
    {name: "Djibouti",currency: "DJF"},
    {name: "Dominica",currency: "XCD"},
    {name: "Dominican Republic",currency: "DOP"},
    {name: "Ecuador",currency: "USD"},
    {name: "Egypt",currency: "EGP"},
    {name: "El Salvador",currency: "USD"},
    {name: "Equatorial Guinea",currency: "XAF"},
    {name: "Eritrea",currency: "ERN"},
    {name: "Estonia",currency: "EUR"},
    {name: "Ethiopia",currency: "ETB"},
    {name: "Falkland Islands (Malvinas)",currency: "FKP"},
    {name: "Faroe Islands",currency: "DKK"},
    {name: "Fiji",currency: "FJD"},
    {name: "Finland",currency: "EUR"},
    {name: "France",currency: "EUR"},
    {name: "French Guiana",currency: "EUR"},
    {name: "French Polynesia",currency: "XPF"},
    {name: "French Southern Territories",currency: "EUR"},
    {name: "Gabon",currency: "XAF"},
    {name: "Gambia",currency: "GMD"},
    {name: "Georgia",currency: "GEL"},
    {name: "Germany",currency: "EUR"},
    {name: "Ghana",currency: "GHS"},
    {name: "Gibraltar",currency: "GIP"},
    {name: "Greece",currency: "EUR"},
    {name: "Greenland",currency: "DKK"},
    {name: "Grenada",currency: "XCD"},
    {name: "Guadeloupe",currency: "EUR"},
    {name: "Guam",currency: "USD"},
    {name: "Guatemala",currency: "GTQ"},
    {name: "Guernsey",currency: "GBP"},
    {name: "Guinea",currency: "GNF"},
    {name: "Guinea-Bissau",currency: "XOF"},
    {name: "Guyana",currency: "GYD"},
    {name: "Haiti",currency: "HTG"},
    {name: "Heard Island and McDonald Islands",currency: "AUD"},
    {name: "Holy See (Vatican City State)",currency: "EUR"},
    {name: "Honduras",currency: "HNL"},
    {name: "Hong Kong",currency: "HKD"},
    {name: "Hungary",currency: "HUF"},
    {name: "Iceland",currency: "ISK"},
    {name: "India",currency: "INR"},
    {name: "Indonesia",currency: "IDR"},
    {name: "Iran, Islamic Republic of",currency: "IRR"},
    {name: "Iraq",currency: "IQD"},
    {name: "Ireland",currency: "EUR"},
    {name: "Isle of Man",currency: "GBP"},
    {name: "Israel",currency: "ILS"},
    {name: "Italy",currency: "EUR"},
    {name: "Jamaica",currency: "JMD"},
    {name: "Japan",currency: "JPY"},
    {name: "Jersey",currency: "GBP"},
    {name: "Jordan",currency: "JOD"},
    {name: "Kazakhstan",currency: "KZT"},
    {name: "Kenya",currency: "KES"},
    {name: "Kiribati",currency: "AUD"},
    {name: "Korea, Democratic People's Republic of",currency: "KPW"},
    {name: "Korea, Republic of",currency: "KRW"},
    {name: "Kosovo",currency: "EUR"},
    {name: "Kuwait",currency: "KWD"},
    {name: "Kyrgyzstan",currency: "KGS"},
    {name: "Lao People's Democratic Republic",currency: "LAK"},
    {name: "Latvia",currency: "EUR"},
    {name: "Lebanon",currency: "LBP"},
    {name: "Lesotho",currency: "LSL"},
    {name: "Liberia",currency: "LRD"},
    {name: "Libyan Arab Jamahiriya",currency: "LYD"},
    {name: "Liechtenstein",currency: "CHF"},
    {name: "Lithuania",currency: "EUR"},
    {name: "Luxembourg",currency: "EUR"},
    {name: "Macao",currency: "MOP"},
    {name: "Macedonia, the Former Yugoslav Republic of",currency: "MKD"},
    {name: "Madagascar",currency: "MGA"},
    {name: "Malawi",currency: "MWK"},
    {name: "Malaysia",currency: "MYR"},
    {name: "Maldives",currency: "MVR"},
    {name: "Mali",currency: "XOF"},
    {name: "Malta",currency: "EUR"},
    {name: "Marshall Islands",currency: "USD"},
    {name: "Martinique",currency: "EUR"},
    {name: "Mauritania",currency: "MRO"},
    {name: "Mauritius",currency: "MUR"},
    {name: "Mayotte",currency: "EUR"},
    {name: "Mexico",currency: "MXN"},
    {name: "Micronesia, Federated States of",currency: "USD"},
    {name: "Moldova, Republic of",currency: "MDL"},
    {name: "Monaco",currency: "EUR"},
    {name: "Mongolia",currency: "MNT"},
    {name: "Montenegro",currency: "EUR"},
    {name: "Montserrat",currency: "XCD"},
    {name: "Morocco",currency: "MAD"},
    {name: "Mozambique",currency: "MZN"},
    {name: "Myanmar",currency: "MMK"},
    {name: "Namibia",currency: "NAD"},
    {name: "Nauru",currency: "AUD"},
    {name: "Nepal",currency: "NPR"},
    {name: "Netherlands",currency: "EUR"},
    {name: "Netherlands Antilles",currency: "ANG"},
    {name: "New Caledonia",currency: "XPF"},
    {name: "New Zealand",currency: "NZD"},
    {name: "Nicaragua",currency: "NIO"},
    {name: "Niger",currency: "XOF"},
    {name: "Nigeria",currency: "NGN"},
    {name: "Niue",currency: "NZD"},
    {name: "Norfolk Island",currency: "AUD"},
    {name: "Northern Mariana Islands",currency: "USD"},
    {name: "Norway",currency: "NOK"},
    {name: "Oman",currency: "OMR"},
    {name: "Pakistan",currency: "PKR"},
    {name: "Palau",currency: "USD"},
    {name: "Palestinian Territory, Occupied",currency: "ILS"},
    {name: "Panama",currency: "PAB"},
    {name: "Papua New Guinea",currency: "PGK"},
    {name: "Paraguay",currency: "PYG"},
    {name: "Peru",currency: "PEN"},
    {name: "Philippines",currency: "PHP"},
    {name: "Pitcairn",currency: "NZD"},
    {name: "Poland",currency: "PLN"},
    {name: "Portugal",currency: "EUR"},
    {name: "Puerto Rico",currency: "USD"},
    {name: "Qatar",currency: "QAR"},
    {name: "Reunion",currency: "EUR"},
    {name: "Romania",currency: "RON"},
    {name: "Russian Federation",currency: "RUB"},
    {name: "Rwanda",currency: "RWF"},
    {name: "Saint Barthelemy",currency: "EUR"},
    {name: "Saint Helena",currency: "SHP"},
    {name: "Saint Kitts and Nevis",currency: "XCD"},
    {name: "Saint Lucia",currency: "XCD"},
    {name: "Saint Martin",currency: "EUR"},
    {name: "Saint Pierre and Miquelon",currency: "EUR"},
    {name: "Saint Vincent and the Grenadines",currency: "XCD"},
    {name: "Samoa",currency: "WST"},
    {name: "San Marino",currency: "EUR"},
    {name: "Sao Tome and Principe",currency: "STD"},
    {name: "Saudi Arabia",currency: "SAR"},
    {name: "Senegal",currency: "XOF"},
    {name: "Serbia",currency: "RSD"},
    {name: "Serbia and Montenegro",currency: "RSD"},
    {name: "Seychelles",currency: "SCR"},
    {name: "Sierra Leone",currency: "SLL"},
    {name: "Singapore",currency: "SGD"},
    {name: "St Martin",currency: "ANG"},
    {name: "Slovakia",currency: "EUR"},
    {name: "Slovenia",currency: "EUR"},
    {name: "Solomon Islands",currency: "SBD"},
    {name: "Somalia",currency: "SOS"},
    {name: "South Africa",currency: "ZAR"},
    {name: "South Georgia and the South Sandwich Islands",currency: "GBP"},
    {name: "South Sudan",currency: "SSP"},
    {name: "Spain",currency: "EUR"},
    {name: "Sri Lanka",currency: "LKR"},
    {name: "Sudan",currency: "SDG"},
    {name: "Suriname",currency: "SRD"},
    {name: "Svalbard and Jan Mayen",currency: "NOK"},
    {name: "Swaziland",currency: "SZL"},
    {name: "Sweden",currency: "SEK"},
    {name: "Switzerland",currency: "CHF"},
    {name: "Syrian Arab Republic",currency: "SYP"},
    {name: "Taiwan, Province of China",currency: "TWD"},
    {name: "Tajikistan",currency: "TJS"},
    {name: "Tanzania, United Republic of",currency: "TZS"},
    {name: "Thailand",currency: "THB"},
    {name: "Timor-Leste",currency: "USD"},
    {name: "Togo",currency: "XOF"},
    {name: "Tokelau",currency: "NZD"},
    {name: "Tonga",currency: "TOP"},
    {name: "Trinidad and Tobago",currency: "TTD"},
    {name: "Tunisia",currency: "TND"},
    {name: "Turkey",currency: "TRY"},
    {name: "Turkmenistan",currency: "TMT"},
    {name: "Turks and Caicos Islands",currency: "USD"},
    {name: "Tuvalu",currency: "AUD"},
    {name: "Uganda",currency: "UGX"},
    {name: "Ukraine",currency: "UAH"},
    {name: "United Arab Emirates",currency: "AED"},
    {name: "United Kingdom",currency: "GBP"},
    {name: "United States",currency: "USD"},
    {name: "United States Minor Outlying Islands",currency: "USD"},
    {name: "Uruguay",currency: "UYU"},
    {name: "Uzbekistan",currency: "UZS"},
    {name: "Vanuatu",currency: "VUV"},
    {name: "Venezuela",currency: "VEF"},
    {name: "Viet Nam",currency: "VND"},
    {name: "Virgin Islands, British",currency: "USD"},
    {name: "Virgin Islands, U.s.",currency: "USD"},
    {name: "Wallis and Futuna",currency: "XPF"},
    {name: "Western Sahara",currency: "MAD"},
    {name: "Yemen",currency: "YER"},
    {name: "Zambia",currency: "ZMW"},
    {name: "Zimbabwe",currency: "ZWL"}
  ];
     
 export const week = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ];
 export const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
 export  const days = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 28,
  ];
  